language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: jPnDhsl2ySCPY3nx536OPrHm7sPhU1zAZwNGkYRVWtAppMTPoSrT/nEHtDQE89rBwjQrUl0FoFD5vRnSgfFtdLR0jSVh4vqTpOPG6yzYy40t9U70fmwqX0WO/SI/7WJfQWnYvmgnNJs3e/YVRkuVlwlLYYBZ4o2waG3vL4J9gyMM0//Axt0j2O+iIgUARagKzSgu3xhXTTupWkuxjigT6NZkE9j+xHwnK5Lsa/0Jymqog76wVttizSjoHW/olrqh10EavG/lpFZz9hHXl6L3JhNAOSw71nanpMsmMaWxZpuVru8LqKX3Agv0OmFyJZ8v0WpAzpEtKLkkFtr86+OV2/WjJ+vZbTJ+mBDYyd4U6scdeq2gmztu6Ax3+EZtvfLKGX8J3TqNi9EReMVdpHonSY5o63Q+8XbO2UVNECo/gvbaik0Gczjr5gzdrdXTI3VriJJslLg6ORAnSQQOI895faznu3ee3bbX9M/4Vx/8EU7WopAmtqK7gd3tDgxLCAj/32+8GulfUnlkNQ9x9McwFoW6xURdXNPeiTY6u8FAdQqMlMzhJWuCZ5nL3kPbcCZRGUi9hrc8ioVa2wOEQM6+Cn7CHg4CzxLXjeKgZEDZUy/1oGYMAnblkv3AuzHPrzWxBvONmMx9ilXRiov8maJtTax3h09cVMR8Qg//aSnlGKo=
  app: devopsnapratica-pipeline100
  edge: true
